--- #YAML:1.0
name:               GitMeta
version:            0.05
abstract:           Clone/update many Git repositories using Meta repos
author:
    - Mike Schilli <cpan@perlmeister.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Temp:       0.22
    Log::Log4perl:    1
    Pithub:           0.01016
    Sysadm::Install:  0.37
    YAML:             0.71
resources:
    repository:  http://github.com/mschilli/gitmeta
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
